buildAll: dsx20 linkx20

dsx20:
	gcc dsx20.c -o dsx20

linkx20:
	gcc linkx20.c -o linkx20

clean:
	find . -type f -iname '*.o' -delete
	find . -type f -iname '*.out' -delete
	find . -type f -iname 'dsx20' -delete
	find . -type f -iname 'linkx20' -delete

